blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Chaosbit/WorkoutApp/blob/main/README.md
    about: Check the README and documentation for usage instructions
  - name: 💬 Discussions
    url: https://github.com/Chaosbit/WorkoutApp/discussions
    about: Ask questions and discuss ideas with the community