name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-unit:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  test-e2e-chrome:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests - Chrome Desktop
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          record: false
          start: python3 -m http.server 8000
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          
      - name: Upload cypress screenshots - Chrome
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots

      - name: Upload cypress videos - Chrome
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-chrome
          path: cypress/videos

  test-e2e-mobile:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Mobile E2E tests - Chrome Mobile
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          record: false
          config-file: cypress.mobile.config.js
          start: python3 -m http.server 8000
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          
      - name: Upload cypress screenshots - Mobile
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-mobile
          path: cypress/screenshots

      - name: Upload cypress videos - Mobile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-mobile
          path: cypress/videos

  # Firefox testing (commented out until Firefox can be reliably installed in CI)
  # test-e2e-firefox:
  #   runs-on: ubuntu-22.04
  #   
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #
  #     - name: Install dependencies
  #       run: npm ci
  #
  #     - name: Install Firefox
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y firefox
  #
  #     - name: Run E2E tests - Firefox
  #       uses: cypress-io/github-action@v6
  #       with:
  #         browser: firefox
  #         headless: true
  #         record: false
  #         start: python3 -m http.server 8000
  #         wait-on: 'http://localhost:8000'
  #         wait-on-timeout: 120