name: Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-unit:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  test-e2e-multi-browser:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
        include:
          - browser: chrome
            browser_name: Chrome
          - browser: firefox
            browser_name: Firefox
          - browser: edge
            browser_name: Microsoft Edge
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firefox (if needed)
        if: matrix.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Microsoft Edge (if needed)
        if: matrix.browser == 'edge'
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
          sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
          sudo apt update
          sudo apt install -y microsoft-edge-stable

      - name: Run E2E tests - ${{ matrix.browser_name }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headless: true
          record: false
          start: python3 -m http.server 8000
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          
      - name: Upload cypress screenshots - ${{ matrix.browser_name }}
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots

      - name: Upload cypress videos - ${{ matrix.browser_name }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: cypress/videos

  test-e2e-mobile:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        viewport: [mobile-chrome, mobile-firefox]
        include:
          - viewport: mobile-chrome
            browser: chrome
            config_file: cypress.mobile.config.js
            viewport_name: Mobile Chrome
          - viewport: mobile-firefox
            browser: firefox
            config_file: cypress.mobile.config.js
            viewport_name: Mobile Firefox
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firefox (if needed)
        if: matrix.browser == 'firefox'
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Run Mobile E2E tests - ${{ matrix.viewport_name }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          headless: true
          record: false
          config-file: ${{ matrix.config_file }}
          start: python3 -m http.server 8000
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          
      - name: Upload cypress screenshots - ${{ matrix.viewport_name }}
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.viewport }}
          path: cypress/screenshots

      - name: Upload cypress videos - ${{ matrix.viewport_name }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.viewport }}
          path: cypress/videos